### ISSUE TITLE
Since phpBB 3.1.6

### ISSUE THREAD

**Issue by Galixte** [bb3mobi/apwa#13]
Hi @bb3mobi,

it seems since phpBB 3.1.6, your extension doesn’t sent any PM.

**Comment by Galixte** [comment]
Hi @bb3mobi,

could you take a look, please ?

**Comment by bb3mobi** [comment]
bb3.mobi - phpbb3.1.6 - tested

The extension will be updated.

**Comment by bb3mobi** [comment]
The expansion will be updated.

**Comment by Galixte** [comment]
Thanks, could you post here to inform me of the update please ?

**Comment by Galixte** [comment]
Hi @bb3mobi,

could you take a look, please ?
