### ISSUE TITLE
The value specified for the "sender" is too high. The value must not exceed 255

### ISSUE THREAD

**Issue by Galixte** [bb3mobi/apwa#15]
Hi @bb3mobi,

could you take a look about this problem, please ?

https://www.phpbb.com/customise/db/extension/private_message_welcome/support/topic/162471?p=496991#p496991

**Comment by Leinad4Mind** [comment]
Solved in my fork

**Comment by Galixte** [comment]
@Leinad4Mind  Will you submit your update instead of the original release on phpBB.com?

**Comment by Leinad4Mind** [comment]
I'll think about it.

**Comment by Scanialady** [comment]
+1

**Comment by Galixte** [comment]
Same answer than previous.

**Comment by eunaumtenhoid** [comment]
ty @Leinad4Mind  PERFECT!

**Comment by Galixte** [comment]
Is it fixed? @Leinad4Mind @Scanialady @eunaumtenhoid

**Comment by Leinad4Mind** [comment]
Yes, you can close it.

**Comment by Galixte** [comment]
Thanks.
